Repository useIceberg/iceberg-editor, pull requests merged in 2020-07, with the labels that each got.

#37 Apply editor theme background color to interface skeleton
  src/styles/ui/ui.scss
Labels: [Type] Enhancement, [Type] Gutenberg

#33 Use heading content as html anchor ID instead of random strings
  src/components/heading-level-indicator/copy-link-menu-item.js
  src/components/heading-level-indicator/indicator.js
  src/components/utils/stripRemovables.js
  src/styles/typography.scss
Labels: [Priority] High, [Type] Enhancement

#15 Fix types in Iceberg_License_Handler
  includes/class-iceberg-license-handler.php
Labels: [Priority] Low, [Type] Code Quality

#35 Additional touchups for WordPress 5.5
  src/components/theme-editor/index.js
  src/components/theme-switcher/index.js
  src/styles/typography.scss
Labels: [Type] WP Core Bug

#13 Fix validate_action
  includes/class-iceberg-license-handler.php
Labels: [Priority] Low, [Type] Code Quality
